replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/visual-defect-service
  tag: "cc358511ccf2d2e2775ff25824683767db3eacdd"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
